name: face_condition_detector
description: A Flutter app that detects a person's face and analyzes its condition in real-time, even in different lighting environments.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+2
  google_ml_kit: ^0.16.2
  image: ^4.0.17
  provider: ^6.0.5
  permission_handler: ^10.3.0
  path_provider: ^2.0.15
  cupertino_icons: ^1.0.2
  tflite: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/models/
