name: face_condition_detector
description: A Flutter app that detects a person's face condition in real-time, even in different lighting environments.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0+4
  google_ml_kit: ^0.13.0
  tflite_flutter: ^0.9.0
  provider: ^6.0.3
  path_provider: ^2.0.11
  image: ^3.2.0
  permission_handler: ^10.0.0
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/models/
